### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by akmallxx** [amiruldev20/Baileys#22]
![Screenshot_2022-11-11-08-12-22-24_dce875ef40efa4e902b2719365b6f678](https://user-images.githubusercontent.com/81015426/201239275-b27711c9-d60d-4fef-9653-d571493ca6a7.jpg)

kaya gitu min pas modulenya di install

**Comment by amiruldev20** [comment]
coba liat package.jsonmu

**Comment by ImYanXiao** [comment]
> 

ada yg bermasalah di package.jsonmu

**Comment by amiruldev20** [comment]
tlg belajar pemahaman dasar dlu & pahami dasar" nodejs sebelum ngebot
