### ISSUE TITLE
[BUG] Pas di npm i malah error bang

### ISSUE THREAD

**Issue by officialdittaz** [amiruldev20/Baileys#25]
Baileys 6.0.4:~ Error: Command failed: npm i @adiwajshing/baileys@https://github.com/amiruldev20/baileys
npm ERR! code 2
npm ERR! git dep preparation failed
npm ERR! command /nix/store/bwxril521b35zlf4x2g32hll64rzfhck-nodejs-16.7.0/bin/node /nix/store/bwxril521b35zlf4x2g32hll64rzfhck-nodejs-16.7.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/runner/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > baileys@6.0.5 prepare
npm ERR! > tsc
npm ERR! 
npm ERR! src/Socket/chats.ts(5,38): error TS2305: Module '"../Utils"' has no exported member 'ChatMutationMap'.
npm ERR! src/Socket/chats.ts(370,34): error TS2339: Property 'mutationMap' does not exist on type '{ state: LTHashState; }'.
npm ERR! src/Socket/chats.ts(375,10): error TS2345: Argument of type 'boolean' is not assignable to parameter of type '(mutation: ChatMutation) => void'.
npm ERR! src/Socket/chats.ts(387,34): error TS2339: Property 'mutationMap' does not exist on type '{ newMutations: ChatMutation[]; state: LTHashState; }'.
npm ERR! src/Socket/chats.ts(392,10): error TS2345: Argument of type 'AxiosRequestConfig<any>' is not assignable to parameter of type '(mut: ChatMutation) => void'.
npm ERR! src/Socket/chats.ts(613,12): error TS2339: Property 'mutationMap' does not exist on type '{ newMutations: ChatMutation[]; state: LTHashState; }'.
npm ERR! src/Socket/chats.ts(618,5): error TS2345: Argument of type 'AxiosRequestConfig<any>' is not assignable to parameter of type '(mut: ChatMutation) => void'.
npm ERR!   Type 'AxiosRequestConfig<any>' provides no match for the signature '(mut: ChatMutation): void'.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! npm ERR! code 2
npm ERR! npm ERR! path /home/runner/.npm/_cacache/tmp/git-clone-683726da
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c tsc
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/runner/.npm/_logs/2022-11-20T14_25_31_232Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-11-20T14_25_33_781Z-debug.log

Apa cuman gua doang yang kek gini ?

**Comment by amiruldev20** [comment]
sudah saya fix. kemaren problem mau fix clearchat

**Comment by officialdittaz** [comment]
Done thanks
