### ISSUE TITLE
[BUG] Buttons Messages

### ISSUE THREAD

**Issue by BrunoSobrino** [amiruldev20/Baileys#6]
In the official baileys of adiwajshing the buttons do not work, in this repository they work? In the pull requets of the official repository there is a solution that is more or less functional, it could be useful in case they don't work. Here is the pull request:

- https://github.com/adiwajshing/Baileys/pull/2674

**Comment by amiruldev20** [comment]
it's not a solution, only a few devices are visible

**Comment by amiruldev20** [comment]
done, update
